server:
  port: 8082

spring:
  application:
    name: trade-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    loadbalancer:
      nacos:
        enabled: true   # 启用Nacos负载均衡
