spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
      discovery:
        locator:
          enabled: true #开启通过服务发现自动创建路由

server:
  port: 9999
